stages:
  preprocess_all:
    cmd: >-
      python run_data_pipeline.py
      --config-path configs/pipeline_profiles_new.yaml
      --profile ${preprocess.profile}
      --params-path params.yaml
      --steps ${preprocess.steps}
      --seed ${preprocess.seed}
    deps:
      - run_data_pipeline.py
      - configs/pipeline_profiles_new.yaml
      - params.yaml
      - datasets/images
      - datasets/labels
    params:
      - preprocess
    outs:
      - ${preprocess.output_base_dir}:
          cache: false
