preprocess:
  profile: pair_1120_1208
  seed: 42
  output_base_dir: data/pipeline_pair_1120_1208_test
  steps: 123456
  dataset_pairs:
  - image_root: datasets/images/1120
    label_root: datasets/labels/1120
  - image_root: datasets/images/1208
    label_root: datasets/labels/1208
  labelme2yolo:
    seg: true
    unify_to_crack: false
  yolo_roi_extractor:
    model_path: ./model/weldROI4.pt
    roi_conf: 0.25
    roi_iou: 0.45
    padding: 0.1
    mode: seg
  patchandenhance:
    overlap: 0.7
    enhance_mode: windowing
    slice_mode: 3
    window_size:
    - 640
    - 640
    label_mode: seg
  seg2det:
    mode: det
    balance_data: false
    balance_ratio: 1.0
  yolo2coco:
    task: det
    test_split_ratio: 0.05
    split_seed: 42
  merge_coco:
    dataset_b: roi2_merge/coco_det
    splits:
    - train
    - valid
    - test
    merge_ratio:
    - 1.0
data:
  tag: crack_v1
  raw_dir: datasets/crack/crack
  yolo_dir: data/processed/crack_yolo
  val_size: 0.1

train:
  epochs: 200
  imgsz: 640
  batch: 8
  lr: 0.001
  output_dir: outputs/welddetect
  run: crack_baseline
  model: yolo11l.pt
  pretrained: true
  degrees: 180
